### ISSUE TITLE
Error on load

### ISSUE THREAD

**Issue by jeaye** [greglook/puget#35] opened 2017-01-10 04:10 UTC
I get this on load, in Clojure 1.9.0-alpha13:

```text
java.lang.IllegalArgumentException: No implementation of method: :visit-nil of protocol: #'fipp.visit/IVisitor found for class: puget.printer.PrettyPrinter
```

I haven't found any reference to this around; is it something you've seen or know how to work around?

**Comment by jeaye** [comment] 2017-01-10 04:16
Looks like it happens whenever I print anything. The value is printed, without color or formatting, and the error shows up. He's an example printing a string:

```text
foo.dev=> (foo.common.debug/pprint "string")
"string"

java.lang.IllegalArgumentException: No implementation of method: :visit-string of protocol: #'fipp.visit/IVisitor found for class: puget.printer.PrettyPrinter
```

**Comment by greglook** [comment] 2017-01-11 04:28
Hmm, that's unexpected - the record definitely does implement that method. I can't reproduce this locally with a project containing just `[org.clojure/clojure "1.9.0-alpha13"]` and `[mvxcvi/puget "1.0.1"]`. Do the dependencies output by `lein deps :tree` look like they're correct?

For the coloring issue - by default, Puget doesn't enable colored output. You'll want to set the `:print-color` option to true by passing it directly to the `pprint` call, using the `with-options` or `with-color` dynamic bindings, or calling `cprint` instead of `pprint`.

**Comment by greglook** [comment] 2017-08-04 04:52
Closing, feel free to reopen if this is still an issue.

**Closed by greglook** 2017-08-04 04:52 UTC
